// Package vectors produces the cross-implementation test vectors in
// ../testdata (repository root). The Foundry tests verify the Go-generated
// Merkle proofs with the Solidity contract, and the Python SDK tests check
// its canonical JSON against the Go canonicalization.
//
// The vectors are golden files: `go test ./internal/vectors` fails if they
// drift from what this code generates. Regenerate with
//
//	go test ./internal/vectors -update
package vectors

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/ronitspatil/verilog/daemon/internal/canonical"
	"github.com/ronitspatil/verilog/daemon/internal/merkle"
)

var update = flag.Bool("update", false, "rewrite the golden vector files")

const testdataDir = "../../../testdata"

func hexes(hs []merkle.Hash) []string {
	out := make([]string, len(hs))
	for i, h := range hs {
		out[i] = canonical.Digest(h).Hex()
	}
	return out
}

type merkleTree struct {
	LeafCount int        `json:"leafCount"`
	Root      string     `json:"root"`
	Leaves    []string   `json:"leaves"`
	Proofs    [][]string `json:"proofs"`
}

type merkleFile struct {
	Comment   string       `json:"comment"`
	TreeCount int          `json:"treeCount"`
	Trees     []merkleTree `json:"trees"`
}

func buildMerkleVectors(t *testing.T) merkleFile {
	sizes := []int{1, 2, 3, 4, 5, 7, 8, 9, 16, 17, 33}
	f := merkleFile{
		Comment: "Generated by daemon/internal/vectors. leaf_i = keccak256(sha256(uint64be(treeSize*1000+i))).",
	}
	for _, n := range sizes {
		digests := make([][32]byte, n)
		for i := range digests {
			var b [8]byte
			binary.BigEndian.PutUint64(b[:], uint64(n*1000+i))
			digests[i] = sha256.Sum256(b[:])
		}
		leaves := merkle.LeavesFromDigests(digests)
		s, err := merkle.Build(leaves)
		if err != nil {
			t.Fatal(err)
		}
		tree := merkleTree{LeafCount: n, Root: canonical.Digest(s.Root()).Hex(), Leaves: hexes(leaves)}
		for i := 0; i < n; i++ {
			p, err := s.Proof(i)
			if err != nil {
				t.Fatal(err)
			}
			tree.Proofs = append(tree.Proofs, hexes(p))
		}
		f.Trees = append(f.Trees, tree)
	}
	f.TreeCount = len(f.Trees)
	return f
}

type canonicalCase struct {
	Name             string `json:"name"`
	AgentID          string `json:"agent_id"`
	StepNumber       uint64 `json:"step_number"`
	EventType        string `json:"event_type"`
	PayloadJSON      string `json:"payload_json"`
	TimestampUTC     string `json:"timestamp_utc"`
	CanonicalPayload string `json:"canonical_payload"`
	CanonicalEvent   string `json:"canonical_event"`
	ContentDigest    string `json:"content_digest"`
	Leaf             string `json:"leaf"`
	AgentKey         string `json:"agent_key"`
}

func buildCanonicalVectors(t *testing.T) []canonicalCase {
	ts := time.Date(2026, 9, 30, 12, 0, 0, 123456789, time.UTC)
	inputs := []struct{ name, agent, typ, payload string }{
		{"simple", "agent-alpha", "llm_start", `{"prompts":["What is 2+2?"],"model":"gpt"}`},
		{"nested_unsorted_whitespace", "agent-alpha", "tool_start", "{ \"tool\" : \"search\" ,\n \"input\" : { \"q\" : \"weather\", \"k\" : 3 } }"},
		{"unicode_and_escapes", "agent-β", "llm_end", `{"text":"café € 😀 <b>&</b>\n\t\"q\"","ctl":"\u0001"}`},
		{"numbers", "agent-alpha", "chain_end", `{"big":123456789012345678901234567890,"neg0":-0,"float":1.50,"exp":1e21,"small":1e-7,"int_as_float":2.0}`},
		{"empty_object_payload", "agent-alpha", "chain_start", `{}`},
		{"array_payload", "agent-alpha", "custom", `[3,1,{"b":null,"a":true},"x"]`},
		{"string_payload", "agent-alpha", "custom", `"just a string"`},
		{"utf16_key_order", "agent-alpha", "custom", `{"€":1,"\r":2,"דּ":3,"1":4,"😀":5,"\u0080":6,"ö":7}`},
	}
	var out []canonicalCase
	for i, in := range inputs {
		ev := canonical.Event{
			AgentID:      in.agent,
			StepNumber:   uint64(i + 1),
			EventType:    in.typ,
			PayloadJSON:  []byte(in.payload),
			TimestampUTC: ts.Add(time.Duration(i) * time.Millisecond),
		}
		payload, err := canonical.CanonicalizeJSON(ev.PayloadJSON)
		if err != nil {
			t.Fatal(err)
		}
		canon, err := ev.Canonical()
		if err != nil {
			t.Fatal(err)
		}
		digest := canonical.ContentDigest(canon)
		out = append(out, canonicalCase{
			Name:             in.name,
			AgentID:          ev.AgentID,
			StepNumber:       ev.StepNumber,
			EventType:        ev.EventType,
			PayloadJSON:      in.payload,
			TimestampUTC:     ev.TimestampUTC.Format(canonical.TimestampLayout),
			CanonicalPayload: string(payload),
			CanonicalEvent:   string(canon),
			ContentDigest:    digest.Hex(),
			Leaf:             canonical.Digest(merkle.LeafFromDigest(digest)).Hex(),
			AgentKey:         canonical.AgentKey(ev.AgentID).Hex(),
		})
	}
	return out
}

func marshal(t *testing.T, v any) []byte {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(v); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

func checkGolden(t *testing.T, name string, got []byte) {
	path := filepath.Join(testdataDir, name)
	if *update {
		if err := os.WriteFile(path, got, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("%v (run `go test ./internal/vectors -update` to create)", err)
	}
	if !bytes.Equal(want, got) {
		t.Fatalf("%s is stale: the hash scheme or canonicalization changed. "+
			"If intended, regenerate with `go test ./internal/vectors -update` and re-run forge and pytest.", path)
	}
}

func TestMerkleVectors(t *testing.T) {
	f := buildMerkleVectors(t)
	// Self-check before writing: every proof verifies.
	for _, tree := range f.Trees {
		root, _ := canonical.ParseDigest(tree.Root)
		for i, l := range tree.Leaves {
			leaf, _ := canonical.ParseDigest(l)
			var proof []merkle.Hash
			for _, p := range tree.Proofs[i] {
				d, _ := canonical.ParseDigest(p)
				proof = append(proof, d)
			}
			if !merkle.Verify(leaf, proof, root) {
				t.Fatalf("tree %d leaf %d: proof does not verify", tree.LeafCount, i)
			}
		}
	}
	checkGolden(t, "merkle_vectors.json", marshal(t, f))
}

func TestCanonicalVectors(t *testing.T) {
	cases := buildCanonicalVectors(t)
	for _, c := range cases {
		ev, err := canonical.ParseEvent([]byte(c.CanonicalEvent))
		if err != nil {
			t.Fatalf("%s: canonical event does not re-parse: %v", c.Name, err)
		}
		again, _ := ev.Canonical()
		if string(again) != c.CanonicalEvent {
			t.Fatalf("%s: canonical form not stable", c.Name)
		}
	}
	checkGolden(t, "canonical_vectors.json", marshal(t, map[string]any{
		"comment": fmt.Sprintf("Generated by daemon/internal/vectors. Timestamps use layout %s.", canonical.TimestampLayout),
		"cases":   cases,
	}))
}
