// Package vectors produces the cross-implementation test vectors in
// ../testdata (repository root). The Foundry tests verify the Go-generated
// Merkle proofs with the Solidity contract, and the Python SDK tests check
// its canonical JSON against the Go canonicalization.
//
// The vectors are golden files: `go test ./internal/vectors` fails if they
// drift from what this code generates. Regenerate with
//
//	go test ./internal/vectors -update
package vectors

import (
	"bytes"
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/ronitspatil/verilog/daemon/internal/canonical"
	"github.com/ronitspatil/verilog/daemon/internal/merkle"
)

var update = flag.Bool("update", false, "rewrite the golden vector files")

const testdataDir = "../../../testdata"

func hexes(hs []merkle.Hash) []string {
	out := make([]string, len(hs))
	for i, h := range hs {
		out[i] = canonical.Digest(h).Hex()
	}
	return out
}

type merkleTree struct {
	LeafCount int        `json:"leafCount"`
	Root      string     `json:"root"`
	Leaves    []string   `json:"leaves"`
	Proofs    [][]string `json:"proofs"`
}

type merkleFile struct {
	Comment   string       `json:"comment"`
	TreeCount int          `json:"treeCount"`
	Trees     []merkleTree `json:"trees"`
}

func buildMerkleVectors(t *testing.T) merkleFile {
	sizes := []int{1, 2, 3, 4, 5, 7, 8, 9, 16, 17, 33}
	f := merkleFile{
		Comment: "Generated by daemon/internal/vectors. leaf_i = keccak256(sha256(uint64be(treeSize*1000+i))).",
	}
	for _, n := range sizes {
		digests := make([][32]byte, n)
		for i := range digests {
			var b [8]byte
			binary.BigEndian.PutUint64(b[:], uint64(n*1000+i))
			digests[i] = sha256.Sum256(b[:])
		}
		leaves := merkle.LeavesFromDigests(digests)
		s, err := merkle.Build(leaves)
		if err != nil {
			t.Fatal(err)
		}
		tree := merkleTree{LeafCount: n, Root: canonical.Digest(s.Root()).Hex(), Leaves: hexes(leaves)}
		for i := 0; i < n; i++ {
			p, err := s.Proof(i)
			if err != nil {
				t.Fatal(err)
			}
			tree.Proofs = append(tree.Proofs, hexes(p))
		}
		f.Trees = append(f.Trees, tree)
	}
	f.TreeCount = len(f.Trees)
	return f
}

// TestSeedHex is the Ed25519 seed every signed vector uses. It is public
// test material; never register it on a real network.
const TestSeedHex = "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60"

func testKey(t *testing.T) ed25519.PrivateKey {
	seed, err := hex.DecodeString(TestSeedHex)
	if err != nil {
		t.Fatal(err)
	}
	return ed25519.NewKeyFromSeed(seed)
}

type canonicalCase struct {
	Name             string `json:"name"`
	AgentID          string `json:"agent_id"`
	RunID            string `json:"run_id"`
	StepNumber       uint64 `json:"step_number"`
	PrevHash         string `json:"prev_hash"`
	EventType        string `json:"event_type"`
	PayloadJSON      string `json:"payload_json"`
	TimestampUTC     string `json:"timestamp_utc"`
	KeyID            string `json:"key_id"`
	CanonicalPayload string `json:"canonical_payload"`
	SigningBytes     string `json:"signing_bytes"`
	Sig              string `json:"sig"`
	CanonicalEvent   string `json:"canonical_event"`
	ContentDigest    string `json:"content_digest"`
	Leaf             string `json:"leaf"`
	AgentKey         string `json:"agent_key"`
}

type vectorInput struct{ name, agent, typ, payload string }

// signChain signs the inputs as one run: step i+1, each prev_hash the digest
// of the previous event, the first one zero.
func signChain(t *testing.T, runID string, inputs []vectorInput) []canonicalCase {
	priv := testKey(t)
	ts := time.Date(2026, 9, 30, 12, 0, 0, 123456789, time.UTC)
	var prev canonical.Digest
	var out []canonicalCase
	for i, in := range inputs {
		ev := canonical.Event{
			AgentID:      in.agent,
			RunID:        runID,
			StepNumber:   uint64(i + 1),
			PrevHash:     prev,
			EventType:    in.typ,
			PayloadJSON:  []byte(in.payload),
			TimestampUTC: ts.Add(time.Duration(i) * time.Millisecond),
		}
		if err := ev.Sign(priv); err != nil {
			t.Fatal(err)
		}
		payload, err := canonical.CanonicalizeJSON(ev.PayloadJSON)
		if err != nil {
			t.Fatal(err)
		}
		msg, err := ev.SigningBytes()
		if err != nil {
			t.Fatal(err)
		}
		canon, err := ev.Canonical()
		if err != nil {
			t.Fatal(err)
		}
		digest := canonical.ContentDigest(canon)
		out = append(out, canonicalCase{
			Name:             in.name,
			AgentID:          ev.AgentID,
			RunID:            ev.RunID,
			StepNumber:       ev.StepNumber,
			PrevHash:         ev.PrevHash.Hex(),
			EventType:        ev.EventType,
			PayloadJSON:      in.payload,
			TimestampUTC:     ev.TimestampUTC.Format(canonical.TimestampLayout),
			KeyID:            ev.KeyID.Hex(),
			CanonicalPayload: string(payload),
			SigningBytes:     string(msg),
			Sig:              "0x" + hex.EncodeToString(ev.Sig),
			CanonicalEvent:   string(canon),
			ContentDigest:    digest.Hex(),
			Leaf:             canonical.Digest(merkle.LeafFromDigest(digest)).Hex(),
			AgentKey:         canonical.AgentKey(ev.AgentID).Hex(),
		})
		prev = digest
	}
	return out
}

func buildCanonicalVectors(t *testing.T) []canonicalCase {
	return signChain(t, "vector-run-canonical", []vectorInput{
		{"simple", "agent-alpha", "llm_start", `{"prompts":["What is 2+2?"],"model":"gpt"}`},
		{"nested_unsorted_whitespace", "agent-alpha", "tool_start", "{ \"tool\" : \"search\" ,\n \"input\" : { \"q\" : \"weather\", \"k\" : 3 } }"},
		{"unicode_and_escapes", "agent-β", "llm_end", `{"text":"café € 😀 <b>&</b>\n\t\"q\"","ctl":"\u0001"}`},
		{"numbers", "agent-alpha", "chain_end", `{"big":123456789012345678901234567890,"neg0":-0,"float":1.50,"exp":1e21,"small":1e-7,"int_as_float":2.0}`},
		{"empty_object_payload", "agent-alpha", "chain_start", `{}`},
		{"array_payload", "agent-alpha", "custom", `[3,1,{"b":null,"a":true},"x"]`},
		{"string_payload", "agent-alpha", "custom", `"just a string"`},
		{"utf16_key_order", "agent-alpha", "custom", `{"€":1,"\r":2,"דּ":3,"1":4,"😀":5,"\u0080":6,"ö":7}`},
	})
}

// buildSignedRun is one complete run as the SDK emits it: callback events,
// an sdk_dropped report and the terminal run_end.
func buildSignedRun(t *testing.T) []canonicalCase {
	return signChain(t, "5f0c6e1e-7a43-4c8e-9a51-0d3b8f2c1a77", []vectorInput{
		{"genesis", "agent-alpha", "chain_start", `{"name":"RunnableSequence","inputs":{"question":"where?"}}`},
		{"llm", "agent-alpha", "llm_end", `{"generations":[[{"text":"Paris","score":0.25}]],"latency_s":1.5e-3}`},
		{"dropped", "agent-alpha", canonical.EventSDKDropped, `{"count":2}`},
		{"chain_end", "agent-alpha", "chain_end", `{"outputs":"sunny in Paris"}`},
		{"run_end", "agent-alpha", canonical.EventRunEnd, `{"steps":4,"status":"ok"}`},
	})
}
func marshal(t *testing.T, v any) []byte {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(v); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

func checkGolden(t *testing.T, name string, got []byte) {
	path := filepath.Join(testdataDir, name)
	if *update {
		if err := os.WriteFile(path, got, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("%v (run `go test ./internal/vectors -update` to create)", err)
	}
	if !bytes.Equal(want, got) {
		t.Fatalf("%s is stale: the hash scheme or canonicalization changed. "+
			"If intended, regenerate with `go test ./internal/vectors -update` and re-run forge and pytest.", path)
	}
}

func TestMerkleVectors(t *testing.T) {
	f := buildMerkleVectors(t)
	// Self-check before writing: every proof verifies.
	for _, tree := range f.Trees {
		root, _ := canonical.ParseDigest(tree.Root)
		for i, l := range tree.Leaves {
			leaf, _ := canonical.ParseDigest(l)
			var proof []merkle.Hash
			for _, p := range tree.Proofs[i] {
				d, _ := canonical.ParseDigest(p)
				proof = append(proof, d)
			}
			if !merkle.Verify(leaf, proof, root) {
				t.Fatalf("tree %d leaf %d: proof does not verify", tree.LeafCount, i)
			}
		}
	}
	checkGolden(t, "merkle_vectors.json", marshal(t, f))
}

func checkCases(t *testing.T, cases []canonicalCase) {
	pub := testKey(t).Public().(ed25519.PublicKey)
	for _, c := range cases {
		ev, err := canonical.ParseEvent([]byte(c.CanonicalEvent))
		if err != nil {
			t.Fatalf("%s: canonical event does not re-parse: %v", c.Name, err)
		}
		again, _ := ev.Canonical()
		if string(again) != c.CanonicalEvent {
			t.Fatalf("%s: canonical form not stable", c.Name)
		}
		if err := ev.VerifySig(pub); err != nil {
			t.Fatalf("%s: signature does not verify: %v", c.Name, err)
		}
	}
}

func TestCanonicalVectors(t *testing.T) {
	cases := buildCanonicalVectors(t)
	checkCases(t, cases)
	checkGolden(t, "canonical_vectors.json", marshal(t, map[string]any{
		"comment": fmt.Sprintf("Generated by daemon/internal/vectors. Canonical event v2: the cases form one signed run. Timestamps use layout %s.",
			canonical.TimestampLayout),
		"seed":  "0x" + TestSeedHex,
		"cases": cases,
	}))
}

func TestSignedVectors(t *testing.T) {
	priv := testKey(t)
	pub := priv.Public().(ed25519.PublicKey)
	run := buildSignedRun(t)
	checkCases(t, run)
	checkGolden(t, "signed_vectors.json", marshal(t, map[string]any{
		"comment": "Generated by daemon/internal/vectors. One complete signed run (hash chain). " +
			"signing_bytes = \"" + strings.TrimSuffix(canonical.SigningDomain, "\n") + "\\n\" || canonical(event without sig); " +
			"sig = ed25519(seed, signing_bytes); key_id = keccak256(public_key); content_digest = sha256(canonical_event).",
		"signing_domain": canonical.SigningDomain,
		"seed":           "0x" + TestSeedHex,
		"public_key":     "0x" + hex.EncodeToString(pub),
		"key_id":         canonical.KeyID(pub).Hex(),
		"run":            run,
	}))
}
