version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: gomod
    directory: /daemon
    schedule:
      interval: weekly
    groups:
      go:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: /sdk/python
    schedule:
      interval: weekly
    groups:
      python:
        patterns: ["*"]
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
    groups:
      submodules:
        patterns: ["*"]
