# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import verilog_pb2 as verilog_dot_v1_dot_verilog__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in verilog/v1/verilog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VeriLogStub:
    """VeriLog ingests agent execution events, commits them into per-agent Merkle
    trees and anchors each sealed tree's root on an EVM chain.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestStream = channel.stream_stream(
                '/verilog.v1.VeriLog/IngestStream',
                request_serializer=verilog_dot_v1_dot_verilog__pb2.LogEvent.SerializeToString,
                response_deserializer=verilog_dot_v1_dot_verilog__pb2.Ack.FromString,
                _registered_method=True)
        self.GetProof = channel.unary_unary(
                '/verilog.v1.VeriLog/GetProof',
                request_serializer=verilog_dot_v1_dot_verilog__pb2.GetProofRequest.SerializeToString,
                response_deserializer=verilog_dot_v1_dot_verilog__pb2.GetProofResponse.FromString,
                _registered_method=True)


class VeriLogServicer:
    """VeriLog ingests agent execution events, commits them into per-agent Merkle
    trees and anchors each sealed tree's root on an EVM chain.
    """

    def IngestStream(self, request_iterator, context):
        """IngestStream is a bidirectional stream: the client sends LogEvents and the
        daemon answers every event with exactly one Ack, in the order received.
        An Ack with accepted=true means the event is durable in the daemon's
        write-ahead log and committed to the agent's open epoch.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProof(self, request, context):
        """GetProof returns the Merkle inclusion proof of one event in an anchored
        epoch. The event is selected by leaf index or by content digest.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VeriLogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestStream': grpc.stream_stream_rpc_method_handler(
                    servicer.IngestStream,
                    request_deserializer=verilog_dot_v1_dot_verilog__pb2.LogEvent.FromString,
                    response_serializer=verilog_dot_v1_dot_verilog__pb2.Ack.SerializeToString,
            ),
            'GetProof': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProof,
                    request_deserializer=verilog_dot_v1_dot_verilog__pb2.GetProofRequest.FromString,
                    response_serializer=verilog_dot_v1_dot_verilog__pb2.GetProofResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'verilog.v1.VeriLog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('verilog.v1.VeriLog', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VeriLog:
    """VeriLog ingests agent execution events, commits them into per-agent Merkle
    trees and anchors each sealed tree's root on an EVM chain.
    """

    @staticmethod
    def IngestStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/verilog.v1.VeriLog/IngestStream',
            verilog_dot_v1_dot_verilog__pb2.LogEvent.SerializeToString,
            verilog_dot_v1_dot_verilog__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProof(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verilog.v1.VeriLog/GetProof',
            verilog_dot_v1_dot_verilog__pb2.GetProofRequest.SerializeToString,
            verilog_dot_v1_dot_verilog__pb2.GetProofResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
