# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: verilog/v1/verilog.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'verilog/v1/verilog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18verilog/v1/verilog.proto\x12\nverilog.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe6\x01\n\x08LogEvent\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x13\n\x0bstep_number\x18\x02 \x01(\x04\x12\x12\n\nevent_type\x18\x03 \x01(\t\x12\x14\n\x0cpayload_json\x18\x04 \x01(\t\x12\x31\n\rtimestamp_utc\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06run_id\x18\x06 \x01(\t\x12\x11\n\tprev_hash\x18\x07 \x01(\x0c\x12\x0e\n\x06key_id\x18\x08 \x01(\x0c\x12\x11\n\tsignature\x18\t \x01(\x0c\x12\x10\n\x08sequence\x18\x0f \x01(\x04\"\x84\x01\n\x03\x41\x63k\x12\x10\n\x08sequence\x18\x01 \x01(\x04\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x16\n\x0e\x63ontent_digest\x18\x04 \x01(\x0c\x12\x0c\n\x04leaf\x18\x05 \x01(\x0c\x12\x11\n\tduplicate\x18\x06 \x01(\x08\x12\x11\n\tretryable\x18\x07 \x01(\x08\"q\n\x0fGetProofRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x10\n\x08\x65poch_id\x18\x02 \x01(\x04\x12\x14\n\nleaf_index\x18\x03 \x01(\x04H\x00\x12\x18\n\x0e\x63ontent_digest\x18\x04 \x01(\x0cH\x00\x42\n\n\x08selector\"\xec\x01\n\x10GetProofResponse\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x11\n\tagent_key\x18\x02 \x01(\x0c\x12\x10\n\x08\x65poch_id\x18\x03 \x01(\x04\x12\x13\n\x0bmerkle_root\x18\x04 \x01(\x0c\x12\x12\n\nleaf_index\x18\x05 \x01(\x04\x12\x0c\n\x04leaf\x18\x06 \x01(\x0c\x12\x16\n\x0e\x63ontent_digest\x18\x07 \x01(\x0c\x12\r\n\x05proof\x18\x08 \x03(\x0c\x12\x1c\n\x14\x63\x61nonical_event_json\x18\t \x01(\t\x12\x0f\n\x07tx_hash\x18\n \x01(\t\x12\x14\n\x0c\x62lock_number\x18\x0b \x01(\x04\x32\x8b\x01\n\x07VeriLog\x12\x39\n\x0cIngestStream\x12\x14.verilog.v1.LogEvent\x1a\x0f.verilog.v1.Ack(\x01\x30\x01\x12\x45\n\x08GetProof\x12\x1b.verilog.v1.GetProofRequest\x1a\x1c.verilog.v1.GetProofResponseB@Z>github.com/ronitspatil/verilog/daemon/gen/verilog/v1;verilogv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'verilog.v1.verilog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/ronitspatil/verilog/daemon/gen/verilog/v1;verilogv1'
  _globals['_LOGEVENT']._serialized_start=74
  _globals['_LOGEVENT']._serialized_end=304
  _globals['_ACK']._serialized_start=307
  _globals['_ACK']._serialized_end=439
  _globals['_GETPROOFREQUEST']._serialized_start=441
  _globals['_GETPROOFREQUEST']._serialized_end=554
  _globals['_GETPROOFRESPONSE']._serialized_start=557
  _globals['_GETPROOFRESPONSE']._serialized_end=793
  _globals['_VERILOG']._serialized_start=796
  _globals['_VERILOG']._serialized_end=935
# @@protoc_insertion_point(module_scope)
